"use client";

import * as React from "react";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { ToolUsageTip } from "@/components/tool-usage-tip";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import {
  Download,
  FileText,
  FileJson,
  Presentation,
  Loader2,
} from "lucide-react";
import { useTrackUsage } from "@/lib/use-track-usage";
import { ProOptionsPanel, ProField } from "@/components/pro-options-panel";

type ExportFormat = "markdown" | "pdf" | "notion" | "slides";
type PdfTheme = "light" | "dark" | "sepia";
type PageSize = "a4" | "letter";

const SAMPLE_CHAT = [
  "User: How do I implement authentication in Next.js?",
  "",
  "Assistant: A few common options:",
  "",
  "1. NextAuth.js — drop-in OAuth providers and sessions.",
  "2. Supabase Auth — email/password, OAuth, magic links, with Postgres + RLS.",
  "3. Custom JWT — roll your own with httpOnly cookies.",
  "",
  "User: Tell me more about Supabase Auth.",
  "",
  "Assistant: Sure — install @supabase/supabase-js, create a client with",
  "your URL and anon key, and use signUp / signInWithPassword / signInWithOAuth.",
  "Combine it with Row Level Security so your database trusts the JWT directly.",
].join("\n");

function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

type PdfOptions = {
  theme: PdfTheme;
  customTitle: string;
  includeFooter: boolean;
  pageSize: PageSize;
};

async function exportPdf(text: string, options: PdfOptions = { theme: "light", customTitle: "", includeFooter: false, pageSize: "a4" }) {
  const { jsPDF } = await import("jspdf");
  const doc = new jsPDF({ unit: "pt", format: options.pageSize });

  const margin = 48;
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const usableWidth = pageWidth - margin * 2;
  const lineHeight = 14;

  // Theme colors
  type RGB = [number, number, number];
  const themeMap: Record<PdfTheme, { bg: RGB; text: RGB }> = {
    light: { bg: [255, 255, 255], text: [0, 0, 0] },
    dark:  { bg: [0, 0, 0],       text: [255, 255, 255] },
    sepia: { bg: [244, 236, 216], text: [58, 50, 42] },
  };
  const { bg, text: textColor } = themeMap[options.theme];

  function paintBackground() {
    doc.setFillColor(bg[0], bg[1], bg[2]);
    doc.rect(0, 0, pageWidth, pageHeight, "F");
    doc.setTextColor(textColor[0], textColor[1], textColor[2]);
  }

  paintBackground();

  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);

  let y = margin;

  // Custom title
  if (options.customTitle.trim()) {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(16);
    doc.text(options.customTitle.trim(), margin, y);
    y += 24;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);
  }

  const lines = doc.splitTextToSize(text, usableWidth);
  const footerMargin = options.includeFooter ? 24 : 0;

  for (const line of lines) {
    if (y + lineHeight > pageHeight - margin - footerMargin) {
      doc.addPage();
      paintBackground();
      y = margin;
    }
    doc.text(line, margin, y);
    y += lineHeight;
  }

  // Footer
  if (options.includeFooter) {
    const totalPages = doc.getNumberOfPages();
    for (let p = 1; p <= totalPages; p++) {
      doc.setPage(p);
      paintBackground();
      // Re-draw content is not needed — jsPDF keeps per-page content;
      // we just need to add footer text on top.
      doc.setFontSize(8);
      doc.setTextColor(textColor[0], textColor[1], textColor[2]);
      const footerText = `Page ${p} of ${totalPages} · Generated by LLMUtils`;
      const textWidth = doc.getTextWidth(footerText);
      doc.text(footerText, (pageWidth - textWidth) / 2, pageHeight - 20);
    }
  }

  doc.save("chat-export.pdf");
}

export default function ChatExporterPage() {
  const trackUsage = useTrackUsage("chat-exporter");
  const [chatText, setChatText] = React.useState(SAMPLE_CHAT);
  const [format, setFormat] = React.useState<ExportFormat>("markdown");
  const [busy, setBusy] = React.useState(false);
  const [done, setDone] = React.useState(false);
  const [error, setError] = React.useState<string | null>(null);

  // Pro PDF options
  const [pdfTheme, setPdfTheme] = React.useState<PdfTheme>("light");
  const [customTitle, setCustomTitle] = React.useState("");
  const [includeFooter, setIncludeFooter] = React.useState(false);
  const [pageSize, setPageSize] = React.useState<PageSize>("a4");

  const isComingSoon = format === "notion" || format === "slides";

  async function handleExport() {
    if (!chatText || isComingSoon) return;
    setBusy(true);
    setError(null);
    try {
      if (format === "markdown") {
        downloadBlob(
          new Blob([chatText], { type: "text/markdown" }),
          "chat-export.md"
        );
      } else if (format === "pdf") {
        await exportPdf(chatText, {
          theme: pdfTheme,
          customTitle,
          includeFooter,
          pageSize,
        });
      }
      setDone(true);
      setTimeout(() => setDone(false), 2500);
      void trackUsage();
    } catch (e) {
      setError(e instanceof Error ? e.message : "Export failed");
    } finally {
      setBusy(false);
    }
  }

  return (
    <div className="container mx-auto px-4 py-8 max-w-4xl">
      <div className="mb-8">
        <h1 className="text-3xl font-bold">Chat Exporter</h1>
        <p className="text-muted-foreground mt-2">
          Save ChatGPT or Claude transcripts as Markdown or PDF.
        </p>
      </div>

      <div className="grid md:grid-cols-2 gap-6">
        <Card>
          <CardHeader>
            <CardTitle>Chat content</CardTitle>
          </CardHeader>
          <CardContent>
            <textarea
              value={chatText}
              onChange={(e) => setChatText(e.target.value)}
              className="w-full min-h-[400px] bg-muted p-4 rounded-md text-sm font-mono resize-y"
            />
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>Export</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="space-y-4">
              <div>
                <p className="text-sm font-medium mb-3">Format</p>
                <div className="grid grid-cols-2 gap-2">
                  <Button
                    variant={format === "markdown" ? "default" : "outline"}
                    onClick={() => setFormat("markdown")}
                    className="justify-start"
                  >
                    <FileText className="h-4 w-4 mr-2" />
                    Markdown
                  </Button>
                  <Button
                    variant={format === "pdf" ? "default" : "outline"}
                    onClick={() => setFormat("pdf")}
                    className="justify-start"
                  >
                    <Download className="h-4 w-4 mr-2" />
                    PDF
                  </Button>
                  <Button
                    variant="outline"
                    onClick={() => setFormat("notion")}
                    className="justify-start relative"
                  >
                    <FileJson className="h-4 w-4 mr-2" />
                    Notion
                    <span className="ml-auto text-[10px] uppercase tracking-wider text-muted-foreground">
                      Soon
                    </span>
                  </Button>
                  <Button
                    variant="outline"
                    onClick={() => setFormat("slides")}
                    className="justify-start relative"
                  >
                    <Presentation className="h-4 w-4 mr-2" />
                    Slides
                    <span className="ml-auto text-[10px] uppercase tracking-wider text-muted-foreground">
                      Soon
                    </span>
                  </Button>
                </div>
              </div>

              <div className="bg-muted/50 p-4 rounded-md text-sm text-muted-foreground">
                {format === "markdown" &&
                  "Saves as .md, preserving code blocks and structure."}
                {format === "pdf" &&
                  "Generates a paginated PDF with monospaced text."}
                {format === "notion" &&
                  "Coming soon. Will create a new Notion page via the Notion API once OAuth is wired up."}
                {format === "slides" &&
                  "Coming soon. Will convert the chat into a Google Slides deck once OAuth is wired up."}
              </div>

              {format === "pdf" && (
                <ProOptionsPanel
                  title="PDF options"
                  description="Customize theme, title, footer, and page size."
                >
                  <ProField label="PDF theme">
                    <div className="flex gap-4">
                      {(["light", "dark", "sepia"] as PdfTheme[]).map((t) => (
                        <label key={t} className="flex items-center gap-2 text-sm cursor-pointer capitalize">
                          <input
                            type="radio"
                            name="pdfTheme"
                            value={t}
                            checked={pdfTheme === t}
                            onChange={() => setPdfTheme(t)}
                            className="accent-primary"
                          />
                          {t}
                        </label>
                      ))}
                    </div>
                  </ProField>

                  <ProField label="Custom title" hint="Rendered at the top of page 1 in 16pt bold.">
                    <Input
                      placeholder="e.g. Auth discussion with Claude"
                      value={customTitle}
                      onChange={(e) => setCustomTitle(e.target.value)}
                    />
                  </ProField>

                  <ProField label="Page size">
                    <Select value={pageSize} onValueChange={(v) => setPageSize(v as PageSize)}>
                      <SelectTrigger className="w-32">
                        <SelectValue />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="a4">A4</SelectItem>
                        <SelectItem value="letter">Letter</SelectItem>
                      </SelectContent>
                    </Select>
                  </ProField>

                  <ProField label="Footer">
                    <label className="flex items-center gap-2 text-sm cursor-pointer">
                      <input
                        type="checkbox"
                        checked={includeFooter}
                        onChange={(e) => setIncludeFooter(e.target.checked)}
                        className="accent-primary"
                      />
                      Include "Page X of Y · Generated by LLMUtils"
                    </label>
                  </ProField>
                </ProOptionsPanel>
              )}

              <Button
                onClick={handleExport}
                disabled={!chatText || busy || isComingSoon}
                className="w-full"
              >
                {busy ? (
                  <>
                    <Loader2 className="h-4 w-4 animate-spin mr-2" />
                    Exporting…
                  </>
                ) : done ? (
                  "Exported!"
                ) : (
                  <>
                    <Download className="h-4 w-4 mr-2" />
                    {isComingSoon
                      ? "Not available yet"
                      : `Export as ${format.charAt(0).toUpperCase()}${format.slice(1)}`}
                  </>
                )}
              </Button>
              {error && (
                <p className="text-sm text-destructive">{error}</p>
              )}
            </div>
          </CardContent>
        </Card>
      </div>

      <ToolUsageTip />

      <div className="mt-4 text-sm text-muted-foreground flex items-center gap-2">
        <Badge variant="secondary">Free: 10 exports/day</Badge>
        <span>Upgrade to Pro for unlimited exports.</span>
      </div>
    </div>
  );
}
